### ISSUE TITLE
Service start failed when moved services into repo

### ISSUE THREAD

**Issue by lxwinspur** [openbmc/phosphor-gpio-monitor#1]
When the service is in bitbake metadata, the symbol of the parameter variable should be `${{xxx}}`, and compiled as `${xxx}`.
Now, we have moved the service to the corresponding repo, but it is still `${{xxx}}` after compiled.
Therefore, the symbol of the parameter variable should be `${xxx}`.

**Comment by lxwinspur** [comment]
this discussion will be tracked by https://github.com/openbmc/openbmc/issues/3627

**Comment by bradbishop** [comment]
thanks for the bug report.  Thanks @geissonator for fixing the bug.  Fixed as of: https://github.com/openbmc/phosphor-gpio-monitor/commit/166ef2de362ba1d297b7c62813beff21226c9ded
